plugins {
    id 'java'
    id 'application'
}

group 'org.example'
version '1.0-SNAPSHOT'

wrapper {
    gradleVersion = '7.2'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'org.swinglabs', name: 'swing-layout', version: '1.0.3'
    implementation group: 'com.intellij', name: 'forms_rt', version: '7.0.3'
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.11.4'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

test {
    useJUnitPlatform()
}

task(runGameInteractive, dependsOn: 'classes', type: JavaExec) {
    mainClass = 'com.shuttersky.liarsdice.GameServer'
    classpath = sourceSets.main.runtimeClasspath
    systemProperty "player0", "com.shuttersky.liarsdice.players.PlayerTruthful"
    systemProperty "player1", "com.shuttersky.liarsdice.players.PlayerSwing"
    systemProperty "timeout", 30
}

task(runGame, dependsOn: 'classes', type: JavaExec) {
    mainClass = 'com.shuttersky.liarsdice.GameServer'
    classpath = sourceSets.main.runtimeClasspath
    systemProperty "player0", "com.shuttersky.liarsdice.players.PlayerTruthful"
    systemProperty "player1", "com.shuttersky.liarsdice.players.PlayerTruthfulJoefitz"
    systemProperty "player2", "com.shuttersky.liarsdice.players.PlayerBluffer"
    systemProperty "timeout", 30
}

//     systemProperty "player2", "com.shuttersky.liarsdice.players.PlayerBluffer"

task(viewGame, dependsOn: 'classes', type: JavaExec) {
    mainClass = 'com.shuttersky.liarsdice.experimental.GameViewer2'
    classpath = sourceSets.main.runtimeClasspath
    systemProperty "timeout", 30
}

task(experimentalViewGame, dependsOn: 'classes', type: JavaExec) {
    mainClass = 'com.shuttersky.liarsdice.experimental.GameViewer2'
    classpath = sourceSets.main.runtimeClasspath
    systemProperty "timeout", 30
}

task(gameViewerTester, dependsOn: 'classes', type: JavaExec) {
    mainClass = 'com.shuttersky.liarsdice.GameViewerTester'
    classpath = sourceSets.main.runtimeClasspath
    systemProperty "timeout", 30
}
