package com.shuttersky.liarsdice.experimental;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class GameViewer2
{
    private JButton exitButton;
    private JButton nextButton;
    private JLabel numDiceLabel;
    private JLabel total1Label;
    private JLabel total2Label;
    private JLabel total3Label;
    private JLabel total4Label;
    private JLabel total5Label;
    private JLabel total6Label;
    public JPanel gameViewerPanel;
    private JLabel p1d1;
    private JLabel p1d2;
    private JLabel p1d3;
    private JLabel p1d4;
    private JLabel p1d5;
    private JLabel playerBidLabel;
    private JLabel p2d1;
    private JLabel p2d2;
    private JLabel p2d3;
    private JLabel p2d4;
    private JLabel p2d5;
    private JLabel p3d1;
    private JLabel p3d2;
    private JLabel p3d3;
    private JLabel p3d4;
    private JLabel p3d5;
    private JLabel p4d1;
    private JLabel p4d2;
    private JLabel p4d3;
    private JLabel p4d4;
    private JLabel p4d5;
    private JLabel p5d1;
    private JLabel p5d2;
    private JLabel p5d3;
    private JLabel p5d4;
    private JLabel p5d5;
    private JLabel p6d1;
    private JLabel p6d2;
    private JLabel p6d3;
    private JLabel p6d4;
    private JLabel p6d5;

    public GameViewer2()
    {
        exitButton.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                System.exit(0);
            }
        });

        createUIComponents();
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("My Form");
            frame.setContentPane(new GameViewer2().gameViewerPanel);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.pack();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }

    private void createUIComponents()
    {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        gameViewerPanel = new JPanel();
        gameViewerPanel.setLayout(new GridLayoutManager(9, 1, new Insets(5, 5, 5, 5), -1, -1));
        gameViewerPanel.setMinimumSize(new Dimension(600, 171));
        gameViewerPanel.setPreferredSize(new Dimension(600, 171));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setFocusCycleRoot(false);
        gameViewerPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(431, 34), null, 0, false));
        exitButton = new JButton();
        exitButton.setText("Exit");
        panel1.add(exitButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        nextButton = new JButton();
        nextButton.setText("Next");
        panel1.add(nextButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        gameViewerPanel.add(spacer2, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(431, 14), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        gameViewerPanel.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel2.setBorder(BorderFactory.createTitledBorder(null, "Stats", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("Total Number of Dice:");
        panel2.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Total of Each Die:");
        panel2.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel3.setPreferredSize(new Dimension(400, 42));
        panel2.add(panel3, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        total1Label = new JLabel();
        total1Label.setHorizontalAlignment(10);
        total1Label.setHorizontalTextPosition(10);
        total1Label.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        total1Label.setPreferredSize(new Dimension(60, 32));
        total1Label.setText("0 x");
        panel3.add(total1Label);
        total2Label = new JLabel();
        total2Label.setHorizontalAlignment(10);
        total2Label.setHorizontalTextPosition(10);
        total2Label.setIcon(new ImageIcon(getClass().getResource("/dice2.png")));
        total2Label.setPreferredSize(new Dimension(60, 32));
        total2Label.setText("0 x");
        panel3.add(total2Label);
        total3Label = new JLabel();
        total3Label.setHorizontalAlignment(10);
        total3Label.setHorizontalTextPosition(10);
        total3Label.setIcon(new ImageIcon(getClass().getResource("/dice3.png")));
        total3Label.setPreferredSize(new Dimension(60, 32));
        total3Label.setText("0 x");
        panel3.add(total3Label);
        total4Label = new JLabel();
        total4Label.setHorizontalAlignment(10);
        total4Label.setHorizontalTextPosition(10);
        total4Label.setIcon(new ImageIcon(getClass().getResource("/dice4.png")));
        total4Label.setPreferredSize(new Dimension(60, 32));
        total4Label.setText("0 x");
        panel3.add(total4Label);
        total5Label = new JLabel();
        total5Label.setHorizontalAlignment(10);
        total5Label.setHorizontalTextPosition(10);
        total5Label.setIcon(new ImageIcon(getClass().getResource("/dice5.png")));
        total5Label.setPreferredSize(new Dimension(60, 32));
        total5Label.setText("0 x");
        panel3.add(total5Label);
        total6Label = new JLabel();
        total6Label.setHorizontalAlignment(10);
        total6Label.setHorizontalTextPosition(10);
        total6Label.setIcon(new ImageIcon(getClass().getResource("/dice6.png")));
        total6Label.setText("0 x");
        panel3.add(total6Label);
        numDiceLabel = new JLabel();
        numDiceLabel.setText("Number of Dice");
        panel2.add(numDiceLabel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        gameViewerPanel.add(panel4, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel4.setBorder(BorderFactory.createTitledBorder(null, "Player", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel4.add(panel5, BorderLayout.WEST);
        p1d1 = new JLabel();
        p1d1.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p1d1.setText("");
        panel5.add(p1d1);
        p1d2 = new JLabel();
        p1d2.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p1d2.setText("");
        panel5.add(p1d2);
        p1d3 = new JLabel();
        p1d3.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p1d3.setText("");
        panel5.add(p1d3);
        p1d4 = new JLabel();
        p1d4.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p1d4.setText("");
        panel5.add(p1d4);
        p1d5 = new JLabel();
        p1d5.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p1d5.setText("");
        panel5.add(p1d5);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 13));
        panel4.add(panel6, BorderLayout.CENTER);
        final JLabel label3 = new JLabel();
        label3.setText("Bid: ");
        label3.setVerticalAlignment(0);
        label3.setVerticalTextPosition(0);
        panel6.add(label3);
        playerBidLabel = new JLabel();
        playerBidLabel.setText("Label");
        panel6.add(playerBidLabel);
        final JLabel label4 = new JLabel();
        label4.setText("Trash Talk");
        panel4.add(label4, BorderLayout.SOUTH);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new BorderLayout(0, 0));
        gameViewerPanel.add(panel7, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel7.setBorder(BorderFactory.createTitledBorder(null, "Player", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel7.add(panel8, BorderLayout.WEST);
        p2d1 = new JLabel();
        p2d1.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p2d1.setText("");
        panel8.add(p2d1);
        p2d2 = new JLabel();
        p2d2.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p2d2.setText("");
        panel8.add(p2d2);
        p2d3 = new JLabel();
        p2d3.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p2d3.setText("");
        panel8.add(p2d3);
        p2d4 = new JLabel();
        p2d4.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p2d4.setText("");
        panel8.add(p2d4);
        p2d5 = new JLabel();
        p2d5.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p2d5.setText("");
        panel8.add(p2d5);
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 13));
        panel7.add(panel9, BorderLayout.CENTER);
        final JLabel label5 = new JLabel();
        label5.setText("Bid: ");
        label5.setVerticalAlignment(0);
        label5.setVerticalTextPosition(0);
        panel9.add(label5);
        final JLabel label6 = new JLabel();
        label6.setText("Label");
        panel9.add(label6);
        final JLabel label7 = new JLabel();
        label7.setText("Trash Talk");
        panel7.add(label7, BorderLayout.SOUTH);
        final JPanel panel10 = new JPanel();
        panel10.setLayout(new BorderLayout(0, 0));
        gameViewerPanel.add(panel10, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel10.setBorder(BorderFactory.createTitledBorder(null, "Player", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel11 = new JPanel();
        panel11.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel10.add(panel11, BorderLayout.WEST);
        p3d1 = new JLabel();
        p3d1.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p3d1.setText("");
        panel11.add(p3d1);
        p3d2 = new JLabel();
        p3d2.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p3d2.setText("");
        panel11.add(p3d2);
        p3d3 = new JLabel();
        p3d3.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p3d3.setText("");
        panel11.add(p3d3);
        p3d4 = new JLabel();
        p3d4.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p3d4.setText("");
        panel11.add(p3d4);
        p3d5 = new JLabel();
        p3d5.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p3d5.setText("");
        panel11.add(p3d5);
        final JPanel panel12 = new JPanel();
        panel12.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 13));
        panel10.add(panel12, BorderLayout.CENTER);
        final JLabel label8 = new JLabel();
        label8.setText("Bid: ");
        label8.setVerticalAlignment(0);
        label8.setVerticalTextPosition(0);
        panel12.add(label8);
        final JLabel label9 = new JLabel();
        label9.setText("Label");
        panel12.add(label9);
        final JLabel label10 = new JLabel();
        label10.setText("Trash Talk");
        panel10.add(label10, BorderLayout.SOUTH);
        final JPanel panel13 = new JPanel();
        panel13.setLayout(new BorderLayout(0, 0));
        gameViewerPanel.add(panel13, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel13.setBorder(BorderFactory.createTitledBorder(null, "Player", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel14 = new JPanel();
        panel14.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel13.add(panel14, BorderLayout.WEST);
        p4d1 = new JLabel();
        p4d1.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p4d1.setText("");
        panel14.add(p4d1);
        p4d2 = new JLabel();
        p4d2.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p4d2.setText("");
        panel14.add(p4d2);
        p4d3 = new JLabel();
        p4d3.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p4d3.setText("");
        panel14.add(p4d3);
        p4d4 = new JLabel();
        p4d4.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p4d4.setText("");
        panel14.add(p4d4);
        p4d5 = new JLabel();
        p4d5.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p4d5.setText("");
        panel14.add(p4d5);
        final JPanel panel15 = new JPanel();
        panel15.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 13));
        panel13.add(panel15, BorderLayout.CENTER);
        final JLabel label11 = new JLabel();
        label11.setText("Bid: ");
        label11.setVerticalAlignment(0);
        label11.setVerticalTextPosition(0);
        panel15.add(label11);
        final JLabel label12 = new JLabel();
        label12.setText("Label");
        panel15.add(label12);
        final JLabel label13 = new JLabel();
        label13.setText("Trash Talk");
        panel13.add(label13, BorderLayout.SOUTH);
        final JPanel panel16 = new JPanel();
        panel16.setLayout(new BorderLayout(0, 0));
        gameViewerPanel.add(panel16, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel16.setBorder(BorderFactory.createTitledBorder(null, "Player", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel17 = new JPanel();
        panel17.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel16.add(panel17, BorderLayout.WEST);
        p5d1 = new JLabel();
        p5d1.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p5d1.setText("");
        panel17.add(p5d1);
        p5d2 = new JLabel();
        p5d2.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p5d2.setText("");
        panel17.add(p5d2);
        p5d3 = new JLabel();
        p5d3.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p5d3.setText("");
        panel17.add(p5d3);
        p5d4 = new JLabel();
        p5d4.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p5d4.setText("");
        panel17.add(p5d4);
        p5d5 = new JLabel();
        p5d5.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p5d5.setText("");
        panel17.add(p5d5);
        final JPanel panel18 = new JPanel();
        panel18.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 13));
        panel16.add(panel18, BorderLayout.CENTER);
        final JLabel label14 = new JLabel();
        label14.setText("Bid: ");
        label14.setVerticalAlignment(0);
        label14.setVerticalTextPosition(0);
        panel18.add(label14);
        final JLabel label15 = new JLabel();
        label15.setText("Label");
        panel18.add(label15);
        final JLabel label16 = new JLabel();
        label16.setText("Trash Talk");
        panel16.add(label16, BorderLayout.SOUTH);
        final JPanel panel19 = new JPanel();
        panel19.setLayout(new BorderLayout(0, 0));
        gameViewerPanel.add(panel19, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel19.setBorder(BorderFactory.createTitledBorder(null, "Player", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel20 = new JPanel();
        panel20.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel19.add(panel20, BorderLayout.WEST);
        p6d1 = new JLabel();
        p6d1.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p6d1.setText("");
        panel20.add(p6d1);
        p6d2 = new JLabel();
        p6d2.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p6d2.setText("");
        panel20.add(p6d2);
        p6d3 = new JLabel();
        p6d3.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p6d3.setText("");
        panel20.add(p6d3);
        p6d4 = new JLabel();
        p6d4.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p6d4.setText("");
        panel20.add(p6d4);
        p6d5 = new JLabel();
        p6d5.setIcon(new ImageIcon(getClass().getResource("/dice1.png")));
        p6d5.setText("");
        panel20.add(p6d5);
        final JPanel panel21 = new JPanel();
        panel21.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 13));
        panel19.add(panel21, BorderLayout.CENTER);
        final JLabel label17 = new JLabel();
        label17.setText("Bid: ");
        label17.setVerticalAlignment(0);
        label17.setVerticalTextPosition(0);
        panel21.add(label17);
        final JLabel label18 = new JLabel();
        label18.setText("Label");
        panel21.add(label18);
        final JLabel label19 = new JLabel();
        label19.setText("Trash Talk");
        panel19.add(label19, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return gameViewerPanel;
    }

}
